apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::756188601678:user/paulohenrique
      username: paulohenrique
      groups:
        - system:masters
