apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::960382207733:role/eksFargatePodeExecution
      username: fargate-profile-test
      groups:
        - system:masters
