apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazing-hideout-1655918479-api
  labels:
    app: amazing-hideout-1655918479-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazing-hideout-1655918479-api
  template:
    metadata:
      labels:
        app: amazing-hideout-1655918479-api
    spec:
      containers:
      - name: eks-cluster-inventa-dev-api
        image: 756188601678.dkr.ecr.us-east-1.amazonaws.com/teste-ecr
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

