apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluste-eks-test-ph-api-deployment
  labels:
    app: cluste-eks-test-ph-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluste-eks-test-ph-api
  template:
    metadata:
      labels:
        app: cluste-eks-test-ph-api
    spec:
      containers:
      - name: cluste-eks-test-ph-api
        image: 756188601678.dkr.ecr.us-east-1.amazonaws.com/ecr-teste-ph:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

