apiVersion: v1
kind: Service
metadata:
  name: eks-cluster-inventa-dev-service
spec:
  selector:
    app: eks-cluster-inventa-dev-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
